Update dedeman.py
peviitor-ro/based_scraper_py pull request #246
Opened 2023-11-11 12:07 UTC by TheMrM

2023-11-11 15:19 UTC, lalalaurentiu requested changes

2023-11-11 15:19 UTC, lalalaurentiu commented on sites/dedeman.py
> +import requests
Repositoriul tău nu este actualizat cu cel de peviitor, șterge-l și forkuieste-l din nou.

2023-11-11 15:19 UTC, lalalaurentiu commented on sites/dedeman.py
> +                job_link='https://recrutare.dedeman.ro/detalii-post?id=' + job['Id']
Lipseste fieldul "county"

2023-11-11 15:19 UTC, lalalaurentiu commented on sites/dedeman.py
> +publish_logo(company, 'https://i.dedeman.ro/dedereact/design/images/logo.svg')
Lipseste Afișarea datelor

2023-11-12 11:14 UTC, davidmondoc approved these changes

2023-11-12 11:15 UTC, davidmondoc approved these changes

2023-11-12 17:47 UTC, closed without merging