Added county
peviitor-ro/based_scraper_py pull request #267
Opened 2023-11-14 09:28 UTC by TheMrM

Implemented county section for the fallowing companies Altom | Avangardesoftware | Cartofiserie | PPT | Tremend

2023-11-15 13:25 UTC, lalalaurentiu requested changes

2023-11-15 13:25 UTC, lalalaurentiu commented on sites/cartofisserie.py
> +    cities = [city.strip() for city in job_location]
Lipsesc orașe .
<img width="1440" alt="Screenshot 2023-11-15 at 15 12 33" src="https://github.com/peviitor-ro/based_scraper_py/assets/67306273/ce39be79-0be2-4d48-8b87-f10959fb7233">
<img width="1440" alt="Screenshot 2023-11-15 at 15 12 45" src="https://github.com/peviitor-ro/based_scraper_py/assets/67306273/7f241c7c-e78d-464b-b701-59fb25f3c68b">

2023-11-15 13:25 UTC, lalalaurentiu commented on sites/tremend.py
> +    if not remote:
joburile nu au orașe, județe sau câmpul remote.
<img width="1440" alt="Screenshot 2023-11-15 at 15 22 43" src="https://github.com/peviitor-ro/based_scraper_py/assets/67306273/a522ff1d-3aa9-4719-ba14-5023a836c667">
<img width="1440" alt="Screenshot 2023-11-15 at 15 24 20" src="https://github.com/peviitor-ro/based_scraper_py/assets/67306273/2fc86ef0-c8b7-470c-8f04-7761e2b1489e">

2023-11-15 13:25 UTC, lalalaurentiu commented on sites/ppt.py
> +    for city in clean_job_location:
Lipsesc Orașe.
<img width="1440" alt="Screenshot 2023-11-15 at 15 17 33" src="https://github.com/peviitor-ro/based_scraper_py/assets/67306273/0c44af70-cccb-448b-921b-9752820a1e93">

2023-11-16 06:11 UTC, TheMrM commented
Cartofiserie scraper results
![image](https://github.com/peviitor-ro/based_scraper_py/assets/128375812/7765e6f0-bb44-483f-9406-57f6e9ab70ea)
Tremend scraper results
![image](https://github.com/peviitor-ro/based_scraper_py/assets/128375812/5dc51409-f2e7-49b0-a47e-99a7e5177fa8)
PPT scraper results
![image](https://github.com/peviitor-ro/based_scraper_py/assets/128375812/6b70499c-2450-46a1-b83b-6648ac64eb54)

2023-11-16 13:44 UTC, lalalaurentiu requested changes

2023-11-16 13:44 UTC, lalalaurentiu commented on sites/tremend.py
> +    remote = 'Remote' in location_text
campus remote trebuie sa conțină strungul "Remote" nu valoarea bool true.
<img width="1440" alt="Screenshot 2023-11-16 at 15 39 38" src="https://github.com/peviitor-ro/based_scraper_py/assets/67306273/90ff13ed-abf0-46a0-a79f-3ac34a59a3c9">

2023-11-16 14:09 UTC, lalalaurentiu approved these changes

2023-11-16 14:09 UTC, merged