rezolvare afisare oras codlea brasov -> codlea
peviitor-ro/based_scraper_py pull request #290
Opened 2023-11-16 19:52 UTC by davidmondoc

2023-11-17 13:51 UTC, lalalaurentiu requested changes

2023-11-17 13:51 UTC, lalalaurentiu commented on sites/draxlmaier.py
Editeaza-l in felul acesta......

```py
from scraper_peviitor import Scraper, Rules, loadingData
import json
from utils import translate_city, acurate_city_and_county
from getCounty import get_county

#Cream o instanta a clasei Scraper
scraper = Scraper("https://d-career.org/Draexlmaier/go/DRÄXLMAIER-Job-Opportunities-in-Romania-%28Romanian%29/4196801/0/?q=&sortColumn=referencedate&sortDirection=desc")
rules = Rules(scraper)

#Cautam numarul de joburi
jobsnumbers = rules.getTag("span", {"class":"paginationLabel"}).find_all("b")[1].text

#Cream o lista cu numerele de joburi de 25 in 25
jobsPerPage = [i for i in range(0 , int(jobsnumbers), 25) ]

#Cream un dictionar in care vom salva joburile
company = {"company": "Draxlmaier"}
finaljobs = list()

acurate_city = acurate_city_and_county(
    Codlea_Brasov = {
        'city':'Codlea',
        'county':'Brasov'
    },
    Satu_Mare = {
        'city':'Satu Mare',
        'county':'Satu Mare'
    }
)

#Pentru fiecare numar din lista, extragem joburile
for jobs in jobsPerPage:
    #Daca numarul de joburi este intre 0 si 25, atunci luam decat pagina 1
    if jobs == 0:
        pageLink = 'https://d-career.org/Draexlmaier/go/DRÄXLMAIER-Job-Opportunities-in-Romania-%28Romanian%29/4196801/?q=&sortColumn=referencedate&sortDirection=desc'
    #Daca numarul de joburi este mai mare decat 25, atunci luam pagina corespunzatoare
    else:
        pageLink = f"https://d-career.org/Draexlmaier/go/DRÄXLMAIER-Job-Opportunities-in-Romania-%28Romanian%29/4196801/{jobs}/?q=&sortColumn=referencedate&sortDirection=desc"

    #Punem link-ul in url-ul scraper-ului
    scraper.url = pageLink

    #Cautam elementele care contin joburile si locatiile
    elements = rules.getTags("tr", {"class":"data-row"})

    #Pentru fiecare job, extragem titlul, link-ul, compania, tara si orasul
    for element in elements:
        job_title = element.find("a", {"class":"jobTitle-link"}).text
        job_link = "https://d-career.org" + element.find("a", {"class":"jobTitle-link"})['href']
        city = translate_city(
            element.find("span", {"class":"jobLocation"}).text.split(',')[0].strip()
        )
        county = None

        if acurate_city.get(city.replace(' ', '_')):
            county = acurate_city.get(city.replace(' ', '_')).get('county')
            city = acurate_city.get(city.replace(' ', '_')).get('city')
            
        else:     
            county = get_county(city)
        
        finaljobs.append({
            'job_title': job_title,
            'job_link': job_link,
            'company': company.get('company'),
            'country': 'Romania',
            'city': city,
            'county':county
        })

#Afisam numarul de joburi
print(json.dumps(finaljobs, indent=4))

#Incarcam joburile in baza de date
loadingData(finaljobs, company.get("company"))
```

2023-11-17 13:51 UTC, lalalaurentiu commented on sites/fedex.py
Editeaza-l in felul acesta...

```py
from scraper_peviitor import Scraper, loadingData
import json
from utils import translate_city
from getCounty import get_county

#Folosim ScraperSelenium deoaarece joburile sunt incarcate prin AJAX
url = 'https://careers.fedex.com/api/jobs?lang=ro-RO&location=Rom%25C3%25A2nia&woe=12&stretch=10&stretchUnit=MILES&page=1&limit=100&sortBy=relevance&descending=false&internal=false&brand=FedEx%20Express%20EU'
scraper = Scraper(url)

jobs = scraper.getJson().get('jobs')

company = {"company": "FedEx"}
finaljobs = list()

#Iteram prin joburi si le adaugam in lista finaljobs
for job in jobs:
    obj = job.get('data')
    job_title = obj.get('title')
    job_link = obj.get('meta_data').get('canonical_url')
    city = translate_city(obj.get("city"))

    if city =='Judetul Cluj':
        city = "Cluj-Napoca"

    county = get_county(city)

    finaljobs.append({
        "job_title": job_title,
        "job_link": job_link,
        "company": company.get("company"),
        "country": "Romania",
        "city": city,
        "county":county
    })

#Afisam numarul de joburi
print(json.dumps(finaljobs, indent=4))

#Incarcam joburile in baza de date
loadingData(finaljobs, company.get("company"))
```

2023-11-18 08:35 UTC, davidmondoc reviewed
am schimbat codul

2023-11-19 10:27 UTC, lalalaurentiu approved these changes

2023-11-19 10:28 UTC, merged