Add company Flanco
peviitor-ro/based_scraper_py pull request #522
Opened 2024-02-22 10:46 UTC by mihai-ciorobitca

2024-02-25 16:01 UTC, lalalaurentiu requested changes

2024-02-25 16:01 UTC, lalalaurentiu commented on scraper_peviitor.py
![Screenshot 2024-02-25 at 17 52 17 (2)](https://github.com/peviitor-ro/based_scraper_py/assets/67306273/0d38230f-1584-49ce-8198-7bf8f34d04aa)

2024-02-25 17:58 UTC, mihai-ciorobitca commented on scraper_peviitor.py
> +            return []
Aveam nevoie de BeautifulSoup cu document.content, cu document.text nu imi mergea scraper-ul, dar acum vad ca merge

2024-02-25 17:58 UTC, mihai-ciorobitca commented on scraper_peviitor.py
Am adaugat si county

2024-02-25 18:39 UTC, lalalaurentiu requested changes

2024-02-25 18:39 UTC, lalalaurentiu commented on sites/flanco.py
> +            "link": job.select_one("div.description div.buttons a").get("href"),
cheile title si link nu sunt valide 
Asa arata un obiect valid.
pot fi stringuri sau liste.
![Screenshot 2024-02-25 at 20 11 16 (2)](https://github.com/peviitor-ro/based_scraper_py/assets/67306273/a1e6c830-4c09-4a1f-96f8-85491b14993b)

```suggestion
            "job_title": job.select_one("div.vp-title h2").get_text(),
            "job_link": job.select_one("div.description div.buttons a").get("href"),
```

2024-02-25 18:39 UTC, lalalaurentiu commented on sites/flanco.py
> +            job_info["county"] = get_county(job_info["city"])
Logica ta e buna dar aplicata intr-un singur loc
```suggestion
        job_info = {
            "job_title": job.select_one("div.vp-title h2").get_text(),
            "job_link": job.select_one("div.description div.buttons a").get("href"),
            "city": job.select_one("div.vp-title div p:nth-child(2)").contents[-1].strip(),
            "county": list(set([get_county(city.strip()) for city in job_info["city"].split(",")])),
            "country": "Romania",
            "company": company,
        }
```

2024-02-26 15:22 UTC, lalalaurentiu requested changes

2024-02-26 15:22 UTC, lalalaurentiu commented on getCounty.py
> +            "Sector 6",
Nu adaugam noi orase deoarece structura asta o folosesc toti scraperisti si vom avea probleme in filtrarea datelor

2024-02-26 15:25 UTC, lalalaurentiu requested changes

2024-02-26 15:25 UTC, lalalaurentiu commented on sites/mobexpert.py
> +        "company": company,
cheile title si link nu sunt valide si lipseste county

2024-12-15 02:57 UTC, closed without merging